name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: Add Source
      run: dotnet nuget add source https://nuget.pkg.github.com/nyghtx/index.json -n github -u NyghtX -p ${{ secrets.API_KEY }} --store-password-in-clear-text
    
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack
      run: dotnet pack --configuration Release
    - name: Publish Core
      run: dotnet nuget push "src/LiquidTemplates/bin/Release/*.nupkg" --skip-duplicate --source github   
    - name: Publish CSharp
      run: dotnet nuget push "src/LiquidTemplates.Csharp/bin/Release/*.nupkg" --skip-duplicate --source github  